# Set theme
remote_theme: daviddarnes/alembic

environment: prod
# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - files

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
  - jekyll-analytics

# Site settings
url: "https://macstepien.github.io/"
baseurl: ""
title: "Maciej Stępień"
description: "Projects"
permalink: pretty
logo: "/pics/logo1.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  - title: Home
    url: /home/
  - title: About
    url: /about/
  - title: Projects
    url: /
  - title: Blog
    url: /blog

# Footer nav
navigation_footer:
  Back to top: "#top"

collections:
  projects:
    output: true
    order:
      - 16_roomac.md
      - 17_furuta_pendulum.md
      - 15_selfdriving_car_eng.md
      - 14_ekf_slam.md
      - 13_human_following_robot.md
      - 12_tank.md
      - 11_hexapod.md
      - 10_luminous_ball.md
      - 9_fuzz_guitar_effect.md
      - 8_tesla_coil.md
      - 7_mapping_robot.md
      - 6_3dviewer.md
      - 5_general_purpose_robot.md
      - 4_electronic_dice.md
      - 3_2dracing.md
      - 2_blu.md
      - 1_command_line_games.md